apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-artifact-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: /srv/nfs/kube-share/mlflow/mlflow-artifact
  persistentVolumeReclaimPolicy: Retain
