apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: /srv/nfs/kube-share/mlflow-db
  persistentVolumeReclaimPolicy: Retain
