apiVersion: v1
kind: PersistentVolume
metadata:
  name: tinyimagenet-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 127.0.0.1
    path: /srv/nfs/kube-share/data/tiny-imagenet-200
  persistentVolumeReclaimPolicy: Retain
