apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinyimagenet-pvc
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  volumeName: tinyimagenet-pv
  storageClassName: ""
