apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: train-output-pvc
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: train-output-pv
  storageClassName: ""
