apiVersion: v1
kind: PersistentVolume
metadata:
  name: train-output-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: /srv/nfs/kube-share/mlflow/temp
  persistentVolumeReclaimPolicy: Retain
